package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Apeyciecaja generated by hbm2java
 */
public class Apeyciecaja  implements java.io.Serializable {


     private Integer idayccaja;
     private Date feyhoape;
     private Date feyhocie;
     private Float result;
     private Set arqueos = new HashSet(0);
     private Set movcajas = new HashSet(0);

    public Apeyciecaja() {
    }

    public Apeyciecaja(Date feyhoape, Date feyhocie, Float result, Set arqueos, Set movcajas) {
       this.feyhoape = feyhoape;
       this.feyhocie = feyhocie;
       this.result = result;
       this.arqueos = arqueos;
       this.movcajas = movcajas;
    }
   
    public Integer getIdayccaja() {
        return this.idayccaja;
    }
    
    public void setIdayccaja(Integer idayccaja) {
        this.idayccaja = idayccaja;
    }
    public Date getFeyhoape() {
        return this.feyhoape;
    }
    
    public void setFeyhoape(Date feyhoape) {
        this.feyhoape = feyhoape;
    }
    public Date getFeyhocie() {
        return this.feyhocie;
    }
    
    public void setFeyhocie(Date feyhocie) {
        this.feyhocie = feyhocie;
    }
    public Float getResult() {
        return this.result;
    }
    
    public void setResult(Float result) {
        this.result = result;
    }
    public Set getArqueos() {
        return this.arqueos;
    }
    
    public void setArqueos(Set arqueos) {
        this.arqueos = arqueos;
    }
    public Set getMovcajas() {
        return this.movcajas;
    }
    
    public void setMovcajas(Set movcajas) {
        this.movcajas = movcajas;
    }




}


