package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA



/**
 * Arqueo generated by hbm2java
 */
public class Arqueo  implements java.io.Serializable {


     private int idarq;
     private Moneda moneda;
     private Apeyciecaja apeyciecaja;
     private Formapago formapago;
     private Float montoant;
     private Float montoact;
     private Float montoensis;
     private Float cotizacion;

    public Arqueo() {
    }

	
    public Arqueo(int idarq, Moneda moneda, Formapago formapago) {
        this.idarq = idarq;
        this.moneda = moneda;
        this.formapago = formapago;
    }
    public Arqueo(int idarq, Moneda moneda, Apeyciecaja apeyciecaja, Formapago formapago, Float montoant, Float montoact, Float montoensis, Float cotizacion) {
       this.idarq = idarq;
       this.moneda = moneda;
       this.apeyciecaja = apeyciecaja;
       this.formapago = formapago;
       this.montoant = montoant;
       this.montoact = montoact;
       this.montoensis = montoensis;
       this.cotizacion = cotizacion;
    }
   
    public int getIdarq() {
        return this.idarq;
    }
    
    public void setIdarq(int idarq) {
        this.idarq = idarq;
    }
    public Moneda getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(Moneda moneda) {
        this.moneda = moneda;
    }
    public Apeyciecaja getApeyciecaja() {
        return this.apeyciecaja;
    }
    
    public void setApeyciecaja(Apeyciecaja apeyciecaja) {
        this.apeyciecaja = apeyciecaja;
    }
    public Formapago getFormapago() {
        return this.formapago;
    }
    
    public void setFormapago(Formapago formapago) {
        this.formapago = formapago;
    }
    public Float getMontoant() {
        return this.montoant;
    }
    
    public void setMontoant(Float montoant) {
        this.montoant = montoant;
    }
    public Float getMontoact() {
        return this.montoact;
    }
    
    public void setMontoact(Float montoact) {
        this.montoact = montoact;
    }
    public Float getMontoensis() {
        return this.montoensis;
    }
    
    public void setMontoensis(Float montoensis) {
        this.montoensis = montoensis;
    }
    public Float getCotizacion() {
        return this.cotizacion;
    }
    
    public void setCotizacion(Float cotizacion) {
        this.cotizacion = cotizacion;
    }




}


