package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cargos generated by hbm2java
 */
public class Cargos  implements java.io.Serializable {


     private int idcargo;
     private String descripcar;
     private Set empleados = new HashSet(0);

    public Cargos() {
    }

	
    public Cargos(int idcargo) {
        this.idcargo = idcargo;
    }
    public Cargos(int idcargo, String descripcar, Set empleados) {
       this.idcargo = idcargo;
       this.descripcar = descripcar;
       this.empleados = empleados;
    }
   
    public int getIdcargo() {
        return this.idcargo;
    }
    
    public void setIdcargo(int idcargo) {
        this.idcargo = idcargo;
    }
    public String getDescripcar() {
        return this.descripcar;
    }
    
    public void setDescripcar(String descripcar) {
        this.descripcar = descripcar;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


