package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA



/**
 * Cliexsub generated by hbm2java
 */
public class Cliexsub  implements java.io.Serializable {


     private int idcliexsub;
     private Subreserva subreserva;
     private Cliente cliente;

    public Cliexsub() {
    }

    public Cliexsub(int idcliexsub, Subreserva subreserva, Cliente cliente) {
       this.idcliexsub = idcliexsub;
       this.subreserva = subreserva;
       this.cliente = cliente;
    }
   
    public int getIdcliexsub() {
        return this.idcliexsub;
    }
    
    public void setIdcliexsub(int idcliexsub) {
        this.idcliexsub = idcliexsub;
    }
    public Subreserva getSubreserva() {
        return this.subreserva;
    }
    
    public void setSubreserva(Subreserva subreserva) {
        this.subreserva = subreserva;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }




}


