package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Descartes generated by hbm2java
 */
public class Descartes  implements java.io.Serializable {


     private int iddescarte;
     private Stockyserv stockyserv;
     private Motivodesc motivodesc;
     private Date fechadesc;
     private Float valordesc;
     private Float cantidaddesc;

    public Descartes() {
    }

	
    public Descartes(int iddescarte, Stockyserv stockyserv) {
        this.iddescarte = iddescarte;
        this.stockyserv = stockyserv;
    }
    public Descartes(int iddescarte, Stockyserv stockyserv, Motivodesc motivodesc, Date fechadesc, Float valordesc, Float cantidaddesc) {
       this.iddescarte = iddescarte;
       this.stockyserv = stockyserv;
       this.motivodesc = motivodesc;
       this.fechadesc = fechadesc;
       this.valordesc = valordesc;
       this.cantidaddesc = cantidaddesc;
    }
   
    public int getIddescarte() {
        return this.iddescarte;
    }
    
    public void setIddescarte(int iddescarte) {
        this.iddescarte = iddescarte;
    }
    public Stockyserv getStockyserv() {
        return this.stockyserv;
    }
    
    public void setStockyserv(Stockyserv stockyserv) {
        this.stockyserv = stockyserv;
    }
    public Motivodesc getMotivodesc() {
        return this.motivodesc;
    }
    
    public void setMotivodesc(Motivodesc motivodesc) {
        this.motivodesc = motivodesc;
    }
    public Date getFechadesc() {
        return this.fechadesc;
    }
    
    public void setFechadesc(Date fechadesc) {
        this.fechadesc = fechadesc;
    }
    public Float getValordesc() {
        return this.valordesc;
    }
    
    public void setValordesc(Float valordesc) {
        this.valordesc = valordesc;
    }
    public Float getCantidaddesc() {
        return this.cantidaddesc;
    }
    
    public void setCantidaddesc(Float cantidaddesc) {
        this.cantidaddesc = cantidaddesc;
    }




}


