package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA



/**
 * Detcompra generated by hbm2java
 */
public class Detcompra  implements java.io.Serializable {


     private int iddetcom;
     private Cabcompra cabcompra;
     private Stockyserv stockyserv;
     private Float precio;
     private Float cantidad;
     private Float xiva;

    public Detcompra() {
    }

	
    public Detcompra(int iddetcom, Cabcompra cabcompra) {
        this.iddetcom = iddetcom;
        this.cabcompra = cabcompra;
    }
    public Detcompra(int iddetcom, Cabcompra cabcompra, Stockyserv stockyserv, Float precio, Float cantidad, Float xiva) {
       this.iddetcom = iddetcom;
       this.cabcompra = cabcompra;
       this.stockyserv = stockyserv;
       this.precio = precio;
       this.cantidad = cantidad;
       this.xiva = xiva;
    }
   
    public int getIddetcom() {
        return this.iddetcom;
    }
    
    public void setIddetcom(int iddetcom) {
        this.iddetcom = iddetcom;
    }
    public Cabcompra getCabcompra() {
        return this.cabcompra;
    }
    
    public void setCabcompra(Cabcompra cabcompra) {
        this.cabcompra = cabcompra;
    }
    public Stockyserv getStockyserv() {
        return this.stockyserv;
    }
    
    public void setStockyserv(Stockyserv stockyserv) {
        this.stockyserv = stockyserv;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Float cantidad) {
        this.cantidad = cantidad;
    }
    public Float getXiva() {
        return this.xiva;
    }
    
    public void setXiva(Float xiva) {
        this.xiva = xiva;
    }




}


