package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Documentos generated by hbm2java
 */
public class Documentos  implements java.io.Serializable {


     private int iddoc;
     private Moneda moneda;
     private Banco banco;
     private Formapago formapago;
     private Float monto;
     private String numerodoc;
     private Date fechavenc;
     private String obsdoc;
     private Character encaja;
     private Set movcajas = new HashSet(0);

    public Documentos() {
    }

	
    public Documentos(int iddoc, Moneda moneda, Formapago formapago) {
        this.iddoc = iddoc;
        this.moneda = moneda;
        this.formapago = formapago;
    }
    public Documentos(int iddoc, Moneda moneda, Banco banco, Formapago formapago, Float monto, String numerodoc, Date fechavenc, String obsdoc, Character encaja, Set movcajas) {
       this.iddoc = iddoc;
       this.moneda = moneda;
       this.banco = banco;
       this.formapago = formapago;
       this.monto = monto;
       this.numerodoc = numerodoc;
       this.fechavenc = fechavenc;
       this.obsdoc = obsdoc;
       this.encaja = encaja;
       this.movcajas = movcajas;
    }
   
    public int getIddoc() {
        return this.iddoc;
    }
    
    public void setIddoc(int iddoc) {
        this.iddoc = iddoc;
    }
    public Moneda getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(Moneda moneda) {
        this.moneda = moneda;
    }
    public Banco getBanco() {
        return this.banco;
    }
    
    public void setBanco(Banco banco) {
        this.banco = banco;
    }
    public Formapago getFormapago() {
        return this.formapago;
    }
    
    public void setFormapago(Formapago formapago) {
        this.formapago = formapago;
    }
    public Float getMonto() {
        return this.monto;
    }
    
    public void setMonto(Float monto) {
        this.monto = monto;
    }
    public String getNumerodoc() {
        return this.numerodoc;
    }
    
    public void setNumerodoc(String numerodoc) {
        this.numerodoc = numerodoc;
    }
    public Date getFechavenc() {
        return this.fechavenc;
    }
    
    public void setFechavenc(Date fechavenc) {
        this.fechavenc = fechavenc;
    }
    public String getObsdoc() {
        return this.obsdoc;
    }
    
    public void setObsdoc(String obsdoc) {
        this.obsdoc = obsdoc;
    }
    public Character getEncaja() {
        return this.encaja;
    }
    
    public void setEncaja(Character encaja) {
        this.encaja = encaja;
    }
    public Set getMovcajas() {
        return this.movcajas;
    }
    
    public void setMovcajas(Set movcajas) {
        this.movcajas = movcajas;
    }




}


