package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private int idempresa;
     private String descri;
     private String telef;
     private String direc;
     private String ruc;
     private Set clientes = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(int idempresa) {
        this.idempresa = idempresa;
    }
    public Empresa(int idempresa, String descri, String telef, String direc, String ruc, Set clientes) {
       this.idempresa = idempresa;
       this.descri = descri;
       this.telef = telef;
       this.direc = direc;
       this.ruc = ruc;
       this.clientes = clientes;
    }
   
    public int getIdempresa() {
        return this.idempresa;
    }
    
    public void setIdempresa(int idempresa) {
        this.idempresa = idempresa;
    }
    public String getDescri() {
        return this.descri;
    }
    
    public void setDescri(String descri) {
        this.descri = descri;
    }
    public String getTelef() {
        return this.telef;
    }
    
    public void setTelef(String telef) {
        this.telef = telef;
    }
    public String getDirec() {
        return this.direc;
    }
    
    public void setDirec(String direc) {
        this.direc = direc;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


