package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private int idgrupo;
     private String descripgru;
     private Set habitacions = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(int idgrupo) {
        this.idgrupo = idgrupo;
    }
    public Grupo(int idgrupo, String descripgru, Set habitacions) {
       this.idgrupo = idgrupo;
       this.descripgru = descripgru;
       this.habitacions = habitacions;
    }
   
    public int getIdgrupo() {
        return this.idgrupo;
    }
    
    public void setIdgrupo(int idgrupo) {
        this.idgrupo = idgrupo;
    }
    public String getDescripgru() {
        return this.descripgru;
    }
    
    public void setDescripgru(String descripgru) {
        this.descripgru = descripgru;
    }
    public Set getHabitacions() {
        return this.habitacions;
    }
    
    public void setHabitacions(Set habitacions) {
        this.habitacions = habitacions;
    }




}


