package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Iva generated by hbm2java
 */
public class Iva  implements java.io.Serializable {


     private int idiva;
     private String desciva;
     private Float porc;
     private Set stockyservs = new HashSet(0);
     private Set varioses = new HashSet(0);

    public Iva() {
    }

	
    public Iva(int idiva) {
        this.idiva = idiva;
    }
    public Iva(int idiva, String desciva, Float porc, Set stockyservs, Set varioses) {
       this.idiva = idiva;
       this.desciva = desciva;
       this.porc = porc;
       this.stockyservs = stockyservs;
       this.varioses = varioses;
    }
   
    public int getIdiva() {
        return this.idiva;
    }
    
    public void setIdiva(int idiva) {
        this.idiva = idiva;
    }
    public String getDesciva() {
        return this.desciva;
    }
    
    public void setDesciva(String desciva) {
        this.desciva = desciva;
    }
    public Float getPorc() {
        return this.porc;
    }
    
    public void setPorc(Float porc) {
        this.porc = porc;
    }
    public Set getStockyservs() {
        return this.stockyservs;
    }
    
    public void setStockyservs(Set stockyservs) {
        this.stockyservs = stockyservs;
    }
    public Set getVarioses() {
        return this.varioses;
    }
    
    public void setVarioses(Set varioses) {
        this.varioses = varioses;
    }




}


