package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Moneda generated by hbm2java
 */
public class Moneda  implements java.io.Serializable {


     private int idmoneda;
     private Pais pais;
     private String moneda;
     private Float compra;
     private Float venta;
     private Set cajas = new HashSet(0);
     private Set movcajas = new HashSet(0);
     private Set arqueos = new HashSet(0);
     private Set documentoses = new HashSet(0);

    public Moneda() {
    }

	
    public Moneda(int idmoneda, Pais pais) {
        this.idmoneda = idmoneda;
        this.pais = pais;
    }
    public Moneda(int idmoneda, Pais pais, String moneda, Float compra, Float venta, Set cajas, Set movcajas, Set arqueos, Set documentoses) {
       this.idmoneda = idmoneda;
       this.pais = pais;
       this.moneda = moneda;
       this.compra = compra;
       this.venta = venta;
       this.cajas = cajas;
       this.movcajas = movcajas;
       this.arqueos = arqueos;
       this.documentoses = documentoses;
    }
   
    public int getIdmoneda() {
        return this.idmoneda;
    }
    
    public void setIdmoneda(int idmoneda) {
        this.idmoneda = idmoneda;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public Float getCompra() {
        return this.compra;
    }
    
    public void setCompra(Float compra) {
        this.compra = compra;
    }
    public Float getVenta() {
        return this.venta;
    }
    
    public void setVenta(Float venta) {
        this.venta = venta;
    }
    public Set getCajas() {
        return this.cajas;
    }
    
    public void setCajas(Set cajas) {
        this.cajas = cajas;
    }
    public Set getMovcajas() {
        return this.movcajas;
    }
    
    public void setMovcajas(Set movcajas) {
        this.movcajas = movcajas;
    }
    public Set getArqueos() {
        return this.arqueos;
    }
    
    public void setArqueos(Set arqueos) {
        this.arqueos = arqueos;
    }
    public Set getDocumentoses() {
        return this.documentoses;
    }
    
    public void setDocumentoses(Set documentoses) {
        this.documentoses = documentoses;
    }




}


