package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Motivoajuste generated by hbm2java
 */
public class Motivoajuste  implements java.io.Serializable {


     private int idmoti;
     private Character aumenta;
     private Character egreso;
     private String descrimoti;
     private Set ajustestocks = new HashSet(0);

    public Motivoajuste() {
    }

	
    public Motivoajuste(int idmoti) {
        this.idmoti = idmoti;
    }
    public Motivoajuste(int idmoti, Character aumenta, Character egreso, String descrimoti, Set ajustestocks) {
       this.idmoti = idmoti;
       this.aumenta = aumenta;
       this.egreso = egreso;
       this.descrimoti = descrimoti;
       this.ajustestocks = ajustestocks;
    }
   
    public int getIdmoti() {
        return this.idmoti;
    }
    
    public void setIdmoti(int idmoti) {
        this.idmoti = idmoti;
    }
    public Character getAumenta() {
        return this.aumenta;
    }
    
    public void setAumenta(Character aumenta) {
        this.aumenta = aumenta;
    }
    public Character getEgreso() {
        return this.egreso;
    }
    
    public void setEgreso(Character egreso) {
        this.egreso = egreso;
    }
    public String getDescrimoti() {
        return this.descrimoti;
    }
    
    public void setDescrimoti(String descrimoti) {
        this.descrimoti = descrimoti;
    }
    public Set getAjustestocks() {
        return this.ajustestocks;
    }
    
    public void setAjustestocks(Set ajustestocks) {
        this.ajustestocks = ajustestocks;
    }




}


