package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Motivodesc generated by hbm2java
 */
public class Motivodesc  implements java.io.Serializable {


     private int idmotivo;
     private String descdesc;
     private Set descarteses = new HashSet(0);

    public Motivodesc() {
    }

	
    public Motivodesc(int idmotivo) {
        this.idmotivo = idmotivo;
    }
    public Motivodesc(int idmotivo, String descdesc, Set descarteses) {
       this.idmotivo = idmotivo;
       this.descdesc = descdesc;
       this.descarteses = descarteses;
    }
   
    public int getIdmotivo() {
        return this.idmotivo;
    }
    
    public void setIdmotivo(int idmotivo) {
        this.idmotivo = idmotivo;
    }
    public String getDescdesc() {
        return this.descdesc;
    }
    
    public void setDescdesc(String descdesc) {
        this.descdesc = descdesc;
    }
    public Set getDescarteses() {
        return this.descarteses;
    }
    
    public void setDescarteses(Set descarteses) {
        this.descarteses = descarteses;
    }




}


