package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Multa generated by hbm2java
 */
public class Multa  implements java.io.Serializable {


     private int idmulta;
     private String descripmul;
     private Float precio;
     private Float costo;
     private Set subresxmuls = new HashSet(0);

    public Multa() {
    }

	
    public Multa(int idmulta) {
        this.idmulta = idmulta;
    }
    public Multa(int idmulta, String descripmul, Float precio, Float costo, Set subresxmuls) {
       this.idmulta = idmulta;
       this.descripmul = descripmul;
       this.precio = precio;
       this.costo = costo;
       this.subresxmuls = subresxmuls;
    }
   
    public int getIdmulta() {
        return this.idmulta;
    }
    
    public void setIdmulta(int idmulta) {
        this.idmulta = idmulta;
    }
    public String getDescripmul() {
        return this.descripmul;
    }
    
    public void setDescripmul(String descripmul) {
        this.descripmul = descripmul;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Float getCosto() {
        return this.costo;
    }
    
    public void setCosto(Float costo) {
        this.costo = costo;
    }
    public Set getSubresxmuls() {
        return this.subresxmuls;
    }
    
    public void setSubresxmuls(Set subresxmuls) {
        this.subresxmuls = subresxmuls;
    }




}


