package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Ocupaciones generated by hbm2java
 */
public class Ocupaciones  implements java.io.Serializable {


     private int idocup;
     private Subtipo subtipo;
     private Estado estado;
     private Habitacion habitacion;
     private Reservacion reservacion;
     private Date fecha;

    public Ocupaciones() {
    }

	
    public Ocupaciones(int idocup, Subtipo subtipo, Estado estado, Habitacion habitacion, Date fecha) {
        this.idocup = idocup;
        this.subtipo = subtipo;
        this.estado = estado;
        this.habitacion = habitacion;
        this.fecha = fecha;
    }
    public Ocupaciones(int idocup, Subtipo subtipo, Estado estado, Habitacion habitacion, Reservacion reservacion, Date fecha) {
       this.idocup = idocup;
       this.subtipo = subtipo;
       this.estado = estado;
       this.habitacion = habitacion;
       this.reservacion = reservacion;
       this.fecha = fecha;
    }
   
    public int getIdocup() {
        return this.idocup;
    }
    
    public void setIdocup(int idocup) {
        this.idocup = idocup;
    }
    public Subtipo getSubtipo() {
        return this.subtipo;
    }
    
    public void setSubtipo(Subtipo subtipo) {
        this.subtipo = subtipo;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }
    public Reservacion getReservacion() {
        return this.reservacion;
    }
    
    public void setReservacion(Reservacion reservacion) {
        this.reservacion = reservacion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


