package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private int idpais;
     private String descrippais;
     private Set monedas = new HashSet(0);
     private Set clientes = new HashSet(0);

    public Pais() {
    }

	
    public Pais(int idpais) {
        this.idpais = idpais;
    }
    public Pais(int idpais, String descrippais, Set monedas, Set clientes) {
       this.idpais = idpais;
       this.descrippais = descrippais;
       this.monedas = monedas;
       this.clientes = clientes;
    }
   
    public int getIdpais() {
        return this.idpais;
    }
    
    public void setIdpais(int idpais) {
        this.idpais = idpais;
    }
    public String getDescrippais() {
        return this.descrippais;
    }
    
    public void setDescrippais(String descrippais) {
        this.descrippais = descrippais;
    }
    public Set getMonedas() {
        return this.monedas;
    }
    
    public void setMonedas(Set monedas) {
        this.monedas = monedas;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


