package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private int idprov;
     private String nombre;
     private String ruc;
     private String direccion;
     private String telefprov;
     private Set cabcompras = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(int idprov) {
        this.idprov = idprov;
    }
    public Proveedor(int idprov, String nombre, String ruc, String direccion, String telefprov, Set cabcompras) {
       this.idprov = idprov;
       this.nombre = nombre;
       this.ruc = ruc;
       this.direccion = direccion;
       this.telefprov = telefprov;
       this.cabcompras = cabcompras;
    }
   
    public int getIdprov() {
        return this.idprov;
    }
    
    public void setIdprov(int idprov) {
        this.idprov = idprov;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefprov() {
        return this.telefprov;
    }
    
    public void setTelefprov(String telefprov) {
        this.telefprov = telefprov;
    }
    public Set getCabcompras() {
        return this.cabcompras;
    }
    
    public void setCabcompras(Set cabcompras) {
        this.cabcompras = cabcompras;
    }




}


