package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Puntosmenu generated by hbm2java
 */
public class Puntosmenu  implements java.io.Serializable {


     private int idpunto;
     private String descrippunto;
     private Set usuarioxpuntos = new HashSet(0);

    public Puntosmenu() {
    }

	
    public Puntosmenu(int idpunto) {
        this.idpunto = idpunto;
    }
    public Puntosmenu(int idpunto, String descrippunto, Set usuarioxpuntos) {
       this.idpunto = idpunto;
       this.descrippunto = descrippunto;
       this.usuarioxpuntos = usuarioxpuntos;
    }
   
    public int getIdpunto() {
        return this.idpunto;
    }
    
    public void setIdpunto(int idpunto) {
        this.idpunto = idpunto;
    }
    public String getDescrippunto() {
        return this.descrippunto;
    }
    
    public void setDescrippunto(String descrippunto) {
        this.descrippunto = descrippunto;
    }
    public Set getUsuarioxpuntos() {
        return this.usuarioxpuntos;
    }
    
    public void setUsuarioxpuntos(Set usuarioxpuntos) {
        this.usuarioxpuntos = usuarioxpuntos;
    }




}


