package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reservacion generated by hbm2java
 */
public class Reservacion  implements java.io.Serializable {


     private int idres;
     private Cliente cliente;
     private Float totalres;
     private Float totalcubierto;
     private Date fechareserva;
     private Date fechainicio;
     private Date fechafin;
     private Character confentrega;
     private Character checkin;
     private Character checkout;
     private Character activa;
     private Float descuento;
     private Set ocupacioneses = new HashSet(0);
     private Set subreservas = new HashSet(0);
     private Set movcajas = new HashSet(0);
     private Set facturas = new HashSet(0);

    public Reservacion() {
    }

	
    public Reservacion(int idres, Cliente cliente) {
        this.idres = idres;
        this.cliente = cliente;
    }
    public Reservacion(int idres, Cliente cliente, Float totalres, Float totalcubierto, Date fechareserva, Date fechainicio, Date fechafin, Character confentrega, Character checkin, Character checkout, Character activa, Float descuento, Set ocupacioneses, Set subreservas, Set movcajas, Set facturas) {
       this.idres = idres;
       this.cliente = cliente;
       this.totalres = totalres;
       this.totalcubierto = totalcubierto;
       this.fechareserva = fechareserva;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.confentrega = confentrega;
       this.checkin = checkin;
       this.checkout = checkout;
       this.activa = activa;
       this.descuento = descuento;
       this.ocupacioneses = ocupacioneses;
       this.subreservas = subreservas;
       this.movcajas = movcajas;
       this.facturas = facturas;
    }
   
    public int getIdres() {
        return this.idres;
    }
    
    public void setIdres(int idres) {
        this.idres = idres;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Float getTotalres() {
        return this.totalres;
    }
    
    public void setTotalres(Float totalres) {
        this.totalres = totalres;
    }
    public Float getTotalcubierto() {
        return this.totalcubierto;
    }
    
    public void setTotalcubierto(Float totalcubierto) {
        this.totalcubierto = totalcubierto;
    }
    public Date getFechareserva() {
        return this.fechareserva;
    }
    
    public void setFechareserva(Date fechareserva) {
        this.fechareserva = fechareserva;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public Character getConfentrega() {
        return this.confentrega;
    }
    
    public void setConfentrega(Character confentrega) {
        this.confentrega = confentrega;
    }
    public Character getCheckin() {
        return this.checkin;
    }
    
    public void setCheckin(Character checkin) {
        this.checkin = checkin;
    }
    public Character getCheckout() {
        return this.checkout;
    }
    
    public void setCheckout(Character checkout) {
        this.checkout = checkout;
    }
    public Character getActiva() {
        return this.activa;
    }
    
    public void setActiva(Character activa) {
        this.activa = activa;
    }
    public Float getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Float descuento) {
        this.descuento = descuento;
    }
    public Set getOcupacioneses() {
        return this.ocupacioneses;
    }
    
    public void setOcupacioneses(Set ocupacioneses) {
        this.ocupacioneses = ocupacioneses;
    }
    public Set getSubreservas() {
        return this.subreservas;
    }
    
    public void setSubreservas(Set subreservas) {
        this.subreservas = subreservas;
    }
    public Set getMovcajas() {
        return this.movcajas;
    }
    
    public void setMovcajas(Set movcajas) {
        this.movcajas = movcajas;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


