package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Rutina generated by hbm2java
 */
public class Rutina  implements java.io.Serializable {


     private int idrut;
     private Empleado empleado;
     private Habitacion habitacion;
     private Date hoini;
     private Date hofin;

    public Rutina() {
    }

	
    public Rutina(int idrut, Empleado empleado) {
        this.idrut = idrut;
        this.empleado = empleado;
    }
    public Rutina(int idrut, Empleado empleado, Habitacion habitacion, Date hoini, Date hofin) {
       this.idrut = idrut;
       this.empleado = empleado;
       this.habitacion = habitacion;
       this.hoini = hoini;
       this.hofin = hofin;
    }
   
    public int getIdrut() {
        return this.idrut;
    }
    
    public void setIdrut(int idrut) {
        this.idrut = idrut;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }
    public Date getHoini() {
        return this.hoini;
    }
    
    public void setHoini(Date hoini) {
        this.hoini = hoini;
    }
    public Date getHofin() {
        return this.hofin;
    }
    
    public void setHofin(Date hofin) {
        this.hofin = hofin;
    }




}


