package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA



/**
 * Stockyservxsubre generated by hbm2java
 */
public class Stockyservxsubre  implements java.io.Serializable {


     private int id1;
     private Stockyserv stockyserv;
     private Subreserva subreserva;
     private Float cantidad;
     private Float precio;

    public Stockyservxsubre() {
    }

	
    public Stockyservxsubre(int id1, Stockyserv stockyserv, Subreserva subreserva) {
        this.id1 = id1;
        this.stockyserv = stockyserv;
        this.subreserva = subreserva;
    }
    public Stockyservxsubre(int id1, Stockyserv stockyserv, Subreserva subreserva, Float cantidad, Float precio) {
       this.id1 = id1;
       this.stockyserv = stockyserv;
       this.subreserva = subreserva;
       this.cantidad = cantidad;
       this.precio = precio;
    }
   
    public int getId1() {
        return this.id1;
    }
    
    public void setId1(int id1) {
        this.id1 = id1;
    }
    public Stockyserv getStockyserv() {
        return this.stockyserv;
    }
    
    public void setStockyserv(Stockyserv stockyserv) {
        this.stockyserv = stockyserv;
    }
    public Subreserva getSubreserva() {
        return this.subreserva;
    }
    
    public void setSubreserva(Subreserva subreserva) {
        this.subreserva = subreserva;
    }
    public Float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Float cantidad) {
        this.cantidad = cantidad;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }




}


