package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA



/**
 * Subresxmul generated by hbm2java
 */
public class Subresxmul  implements java.io.Serializable {


     private int id2;
     private Multa multa;
     private Subreserva subreserva;
     private Float cantidad;
     private Float precio;

    public Subresxmul() {
    }

	
    public Subresxmul(int id2, Multa multa, Subreserva subreserva) {
        this.id2 = id2;
        this.multa = multa;
        this.subreserva = subreserva;
    }
    public Subresxmul(int id2, Multa multa, Subreserva subreserva, Float cantidad, Float precio) {
       this.id2 = id2;
       this.multa = multa;
       this.subreserva = subreserva;
       this.cantidad = cantidad;
       this.precio = precio;
    }
   
    public int getId2() {
        return this.id2;
    }
    
    public void setId2(int id2) {
        this.id2 = id2;
    }
    public Multa getMulta() {
        return this.multa;
    }
    
    public void setMulta(Multa multa) {
        this.multa = multa;
    }
    public Subreserva getSubreserva() {
        return this.subreserva;
    }
    
    public void setSubreserva(Subreserva subreserva) {
        this.subreserva = subreserva;
    }
    public Float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Float cantidad) {
        this.cantidad = cantidad;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }




}


