package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Subreserva generated by hbm2java
 */
public class Subreserva  implements java.io.Serializable {


     private int idsubres;
     private Subtipo subtipo;
     private Habitacion habitacion;
     private Reservacion reservacion;
     private Date fechaocup;
     private Date fechadesoc;
     private Date feyhocheckin;
     private Date feyhocheckout;
     private Float subtotalhosp;
     private Float subtotconsum;
     private Float montoabonado;
     private Character escorta;
     private Set cliexsubs = new HashSet(0);
     private Set stockyservxsubres = new HashSet(0);
     private Set subresxmuls = new HashSet(0);

    public Subreserva() {
    }

	
    public Subreserva(int idsubres, Subtipo subtipo, Habitacion habitacion, Reservacion reservacion) {
        this.idsubres = idsubres;
        this.subtipo = subtipo;
        this.habitacion = habitacion;
        this.reservacion = reservacion;
    }
    public Subreserva(int idsubres, Subtipo subtipo, Habitacion habitacion, Reservacion reservacion, Date fechaocup, Date fechadesoc, Date feyhocheckin, Date feyhocheckout, Float subtotalhosp, Float subtotconsum, Float montoabonado, Character escorta, Set cliexsubs, Set stockyservxsubres, Set subresxmuls) {
       this.idsubres = idsubres;
       this.subtipo = subtipo;
       this.habitacion = habitacion;
       this.reservacion = reservacion;
       this.fechaocup = fechaocup;
       this.fechadesoc = fechadesoc;
       this.feyhocheckin = feyhocheckin;
       this.feyhocheckout = feyhocheckout;
       this.subtotalhosp = subtotalhosp;
       this.subtotconsum = subtotconsum;
       this.montoabonado = montoabonado;
       this.escorta = escorta;
       this.cliexsubs = cliexsubs;
       this.stockyservxsubres = stockyservxsubres;
       this.subresxmuls = subresxmuls;
    }
   
    public int getIdsubres() {
        return this.idsubres;
    }
    
    public void setIdsubres(int idsubres) {
        this.idsubres = idsubres;
    }
    public Subtipo getSubtipo() {
        return this.subtipo;
    }
    
    public void setSubtipo(Subtipo subtipo) {
        this.subtipo = subtipo;
    }
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }
    public Reservacion getReservacion() {
        return this.reservacion;
    }
    
    public void setReservacion(Reservacion reservacion) {
        this.reservacion = reservacion;
    }
    public Date getFechaocup() {
        return this.fechaocup;
    }
    
    public void setFechaocup(Date fechaocup) {
        this.fechaocup = fechaocup;
    }
    public Date getFechadesoc() {
        return this.fechadesoc;
    }
    
    public void setFechadesoc(Date fechadesoc) {
        this.fechadesoc = fechadesoc;
    }
    public Date getFeyhocheckin() {
        return this.feyhocheckin;
    }
    
    public void setFeyhocheckin(Date feyhocheckin) {
        this.feyhocheckin = feyhocheckin;
    }
    public Date getFeyhocheckout() {
        return this.feyhocheckout;
    }
    
    public void setFeyhocheckout(Date feyhocheckout) {
        this.feyhocheckout = feyhocheckout;
    }
    public Float getSubtotalhosp() {
        return this.subtotalhosp;
    }
    
    public void setSubtotalhosp(Float subtotalhosp) {
        this.subtotalhosp = subtotalhosp;
    }
    public Float getSubtotconsum() {
        return this.subtotconsum;
    }
    
    public void setSubtotconsum(Float subtotconsum) {
        this.subtotconsum = subtotconsum;
    }
    public Float getMontoabonado() {
        return this.montoabonado;
    }
    
    public void setMontoabonado(Float montoabonado) {
        this.montoabonado = montoabonado;
    }
    public Character getEscorta() {
        return this.escorta;
    }
    
    public void setEscorta(Character escorta) {
        this.escorta = escorta;
    }
    public Set getCliexsubs() {
        return this.cliexsubs;
    }
    
    public void setCliexsubs(Set cliexsubs) {
        this.cliexsubs = cliexsubs;
    }
    public Set getStockyservxsubres() {
        return this.stockyservxsubres;
    }
    
    public void setStockyservxsubres(Set stockyservxsubres) {
        this.stockyservxsubres = stockyservxsubres;
    }
    public Set getSubresxmuls() {
        return this.subresxmuls;
    }
    
    public void setSubresxmuls(Set subresxmuls) {
        this.subresxmuls = subresxmuls;
    }




}


