package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipohab generated by hbm2java
 */
public class Tipohab  implements java.io.Serializable {


     private int idtipoh;
     private String descripth;
     private int cantadultos;
     private int cantninos;
     private Set habitacions = new HashSet(0);

    public Tipohab() {
    }

	
    public Tipohab(int idtipoh, String descripth, int cantadultos, int cantninos) {
        this.idtipoh = idtipoh;
        this.descripth = descripth;
        this.cantadultos = cantadultos;
        this.cantninos = cantninos;
    }
    public Tipohab(int idtipoh, String descripth, int cantadultos, int cantninos, Set habitacions) {
       this.idtipoh = idtipoh;
       this.descripth = descripth;
       this.cantadultos = cantadultos;
       this.cantninos = cantninos;
       this.habitacions = habitacions;
    }
   
    public int getIdtipoh() {
        return this.idtipoh;
    }
    
    public void setIdtipoh(int idtipoh) {
        this.idtipoh = idtipoh;
    }
    public String getDescripth() {
        return this.descripth;
    }
    
    public void setDescripth(String descripth) {
        this.descripth = descripth;
    }
    public int getCantadultos() {
        return this.cantadultos;
    }
    
    public void setCantadultos(int cantadultos) {
        this.cantadultos = cantadultos;
    }
    public int getCantninos() {
        return this.cantninos;
    }
    
    public void setCantninos(int cantninos) {
        this.cantninos = cantninos;
    }
    public Set getHabitacions() {
        return this.habitacions;
    }
    
    public void setHabitacions(Set habitacions) {
        this.habitacions = habitacions;
    }




}


