package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Unidadmedida generated by hbm2java
 */
public class Unidadmedida  implements java.io.Serializable {


     private int idum;
     private String descripum;
     private Set stockyservs = new HashSet(0);

    public Unidadmedida() {
    }

	
    public Unidadmedida(int idum) {
        this.idum = idum;
    }
    public Unidadmedida(int idum, String descripum, Set stockyservs) {
       this.idum = idum;
       this.descripum = descripum;
       this.stockyservs = stockyservs;
    }
   
    public int getIdum() {
        return this.idum;
    }
    
    public void setIdum(int idum) {
        this.idum = idum;
    }
    public String getDescripum() {
        return this.descripum;
    }
    
    public void setDescripum(String descripum) {
        this.descripum = descripum;
    }
    public Set getStockyservs() {
        return this.stockyservs;
    }
    
    public void setStockyservs(Set stockyservs) {
        this.stockyservs = stockyservs;
    }




}


