package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int idusuario;
     private Empleado empleado;
     private String usuario;
     private String pass;
     private Set usuarioxpuntos = new HashSet(0);
     private Set varioses = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(int idusuario, String usuario, String pass) {
        this.idusuario = idusuario;
        this.usuario = usuario;
        this.pass = pass;
    }
    public Usuarios(int idusuario, Empleado empleado, String usuario, String pass, Set usuarioxpuntos, Set varioses) {
       this.idusuario = idusuario;
       this.empleado = empleado;
       this.usuario = usuario;
       this.pass = pass;
       this.usuarioxpuntos = usuarioxpuntos;
       this.varioses = varioses;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Set getUsuarioxpuntos() {
        return this.usuarioxpuntos;
    }
    
    public void setUsuarioxpuntos(Set usuarioxpuntos) {
        this.usuarioxpuntos = usuarioxpuntos;
    }
    public Set getVarioses() {
        return this.varioses;
    }
    
    public void setVarioses(Set varioses) {
        this.varioses = varioses;
    }




}


