package Hiber1;
// Generated 09-ene-2012 14:16:06 by Hibernate Tools 3.2.1.GA



/**
 * Usuarioxpunto generated by hbm2java
 */
public class Usuarioxpunto  implements java.io.Serializable {


     private int idusuarioxpunto;
     private Usuarios usuarios;
     private Puntosmenu puntosmenu;

    public Usuarioxpunto() {
    }

    public Usuarioxpunto(int idusuarioxpunto, Usuarios usuarios, Puntosmenu puntosmenu) {
       this.idusuarioxpunto = idusuarioxpunto;
       this.usuarios = usuarios;
       this.puntosmenu = puntosmenu;
    }
   
    public int getIdusuarioxpunto() {
        return this.idusuarioxpunto;
    }
    
    public void setIdusuarioxpunto(int idusuarioxpunto) {
        this.idusuarioxpunto = idusuarioxpunto;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Puntosmenu getPuntosmenu() {
        return this.puntosmenu;
    }
    
    public void setPuntosmenu(Puntosmenu puntosmenu) {
        this.puntosmenu = puntosmenu;
    }




}


