import Hiber1.NewHibernateUtil;
import Soporte.ClaseReporte;
import Soporte.clasesutiles;
import java.text.ParseException;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import org.hibernate.SQLQuery;
import org.hibernate.Session;
public class FrmInformeIngresosEgresos extends javax.swing.JDialog {

    /** Creates new form FrmInformeIngresosEgresos */
    public FrmInformeIngresosEgresos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton8 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setName(""); // NOI18N

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 36));
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Informes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.setName(""); // NOI18N

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salir2.png"))); // NOI18N
        jButton9.setToolTipText("SALIR");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)), "Selección de informes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 153))); // NOI18N

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Ingresos y Egresos");
        jRadioButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton1StateChanged(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton2.setText("Ingresos por Cobros realizados");
        jRadioButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton2StateChanged(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jRadioButton3.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton3.setText("Ingresos por ajustes (+) de Stock");
        jRadioButton3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton3StateChanged(evt);
            }
        });
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jRadioButton5.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton5.setText("Egresos por costos de asignación de multas");
        jRadioButton5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton5StateChanged(evt);
            }
        });

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jRadioButton4.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton4.setText("Egresos por costos por venta de productos y servicios");
        jRadioButton4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton4StateChanged(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 14));
        jLabel22.setForeground(new java.awt.Color(0, 0, 204));
        jLabel22.setText("Evaluar resultados:");

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 0, 14));
        jLabel23.setForeground(new java.awt.Color(0, 0, 204));
        jLabel23.setText("Inicio:");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setToolTipText("FECHA DE INICIO DE LA BÚSQUEDA");
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        jFormattedTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField1FocusLost(evt);
            }
        });
        jFormattedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField1KeyReleased(evt);
            }
        });

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField2.setToolTipText("FECHA DE FINALIZACIÓN DE LA BÚSQUEDA");
        jFormattedTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField2FocusLost(evt);
            }
        });
        jFormattedTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField2KeyReleased(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 0, 14));
        jLabel24.setForeground(new java.awt.Color(0, 0, 204));
        jLabel24.setText("Fin:");

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 1, 14));
        jLabel25.setForeground(new java.awt.Color(0, 0, 204));
        jLabel25.setText("Entre fechas:");

        jButton1.setText("Evaluar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 0, 12));
        jRadioButton6.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton6.setText("Egresos registrados con movimientos de caja");
        jRadioButton6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton6StateChanged(evt);
            }
        });
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton7.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 0, 12));
        jRadioButton7.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton7.setText("Egresos por ajustes (-) de Stock");
        jRadioButton7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton7StateChanged(evt);
            }
        });

        jLabel1.setText("* Obs.: El mensaje \"El documento no tiene páginas\" ");

        jLabel2.setText(" indica que no se obtuvo ningún resultado.");

        jRadioButton8.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Tahoma", 0, 12));
        jRadioButton8.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton8.setText("Egresos por descartes registrados");
        jRadioButton8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton8StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton5)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel25)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel23))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButton1)
                            .addComponent(jLabel22)))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton8))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jRadioButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(8, 8, 8)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    clasesutiles cluti=new clasesutiles();
    ClaseReporte cr=new ClaseReporte();
    String fechadehoy="";
    Session Sesion=NewHibernateUtil.getSessionFactory().getCurrentSession();


    public void actualizarFechaDeHoy(){
            fechadehoy=cluti.Date_StringDMA(clasesutiles.Calender_Date(Calendar.getInstance()));
        }

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        //BOTON SALIR
        this.dispose();//sale
}//GEN-LAST:event_jButton9MouseClicked

    private void jRadioButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton1StateChanged

}//GEN-LAST:event_jRadioButton1StateChanged

    private void jRadioButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton2StateChanged

}//GEN-LAST:event_jRadioButton2StateChanged

    private void jRadioButton3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton3StateChanged

}//GEN-LAST:event_jRadioButton3StateChanged

    private void jRadioButton5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton5StateChanged

}//GEN-LAST:event_jRadioButton5StateChanged

    private void jRadioButton4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton4StateChanged

}//GEN-LAST:event_jRadioButton4StateChanged

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField1FocusLost
        //cuadro de fecha1
        String texto1=jFormattedTextField1.getText();
        String texto2=jFormattedTextField2.getText();
        if(texto1.equals("  /  /    ")==false){  //si no esta vacio
            if(cluti.FechaValidaDMA(texto1)==false){  //si la fecha no es valida
                JOptionPane.showMessageDialog(null,"Fecha NO válida","ATENCIÓN",JOptionPane.INFORMATION_MESSAGE);
                jFormattedTextField1.requestFocus();
                jFormattedTextField1.setText("");
            }else{
                if(cluti.obtenerDiferenciaDeFechasEnDias2(texto1, texto2)>=0 && texto2.equals("  /  /    ")==false){  //si la fecha no es valida
                    JOptionPane.showMessageDialog(null,"La fecha de Inicio debe ser menor a la de Fin","ATENCIÓN",JOptionPane.INFORMATION_MESSAGE);
                    jFormattedTextField1.requestFocus();
                    jFormattedTextField1.setText("");
                }
            }

        }
}//GEN-LAST:event_jFormattedTextField1FocusLost

    private void jFormattedTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField1KeyReleased
        // texto fecha1
        if(((int)evt.getKeyChar()) == 10) //si se presiono enter
            jFormattedTextField1.transferFocus();
}//GEN-LAST:event_jFormattedTextField1KeyReleased

    private void jFormattedTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField2FocusLost
        //cuadro de fecha2
        String texto1=jFormattedTextField1.getText();
        String texto2=jFormattedTextField2.getText();
        if(texto2.equals("  /  /    ")==false){  //si no esta vacio
            if(cluti.FechaValidaDMA(texto2)==false){  //si la fecha no es valida
                JOptionPane.showMessageDialog(null,"Fecha NO válida","ATENCIÓN",JOptionPane.INFORMATION_MESSAGE);
                jFormattedTextField2.requestFocus();
                jFormattedTextField2.setText("");
            }else{
                if(cluti.obtenerDiferenciaDeFechasEnDias2(texto1, texto2)>=0 && texto1.equals("  /  /    ")==false){  //si la fecha no es valida
                    JOptionPane.showMessageDialog(null,"La fecha de Fin debe ser mayor a la de Inicio","ATENCIÓN",JOptionPane.INFORMATION_MESSAGE);
                    jFormattedTextField2.requestFocus();
                    jFormattedTextField2.setText("");
                }
            }

        }
}//GEN-LAST:event_jFormattedTextField2FocusLost

    private void jFormattedTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField2KeyReleased
        // texto fecha2
        if(((int)evt.getKeyChar()) == 10) //si se presiono enter
            jFormattedTextField2.transferFocus();
}//GEN-LAST:event_jFormattedTextField2KeyReleased

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.jRadioButton1.isSelected() && this.jFormattedTextField1.getText().equals("  /  /    ")==false && this.jFormattedTextField2.getText().equals("  /  /    ")==false){
            Sesion=NewHibernateUtil.getSessionFactory().openSession();
            Sesion.beginTransaction();
            ///////////////////ingreso1////////////////////////////////
            SQLQuery q=Sesion.createSQLQuery("select sum(r.totalcubierto) from reservacion as r where r.checkout = '1' and r.fechafin >= '"+cluti.FormatearFecha(this.jFormattedTextField1.getText())+"' and r.fechafin <= '"+cluti.FormatearFecha(this.jFormattedTextField2.getText())+"'");
            Object ob=q.uniqueResult();
            float ing1=Float.parseFloat("0.0");
            if(ob != null)
                ing1=Float.parseFloat(ob.toString());
            //////////////////////////////ingreso2///////////////////////////////
            SQLQuery q2=Sesion.createSQLQuery("select sum(a.cant*a.valor) from ajustestock as a inner join motivoajuste as m on a.idmoti = m.idmoti where m.aumenta = '1' and a.feyho >= '"+cluti.FormatearFecha(this.jFormattedTextField1.getText())+"' and a.feyho <= '"+cluti.FormatearFecha(this.jFormattedTextField2.getText())+"'");
            ob=q2.uniqueResult();
            float ing2=Float.parseFloat("0.0");
            if(ob != null)
                ing2=Float.parseFloat(ob.toString());
            //////////////////////////////egreso1//////////////////////////////////
            SQLQuery q31=Sesion.createSQLQuery("select sum(sx.cantidad*sx.precio) as suma from stockyserv as s inner join stockyservxsubre as sx on s.codigo = sx.codigo inner join subreserva as su on sx.idsubres = su.idsubres inner join reservacion as r on r.idres = su.idres where r.fechafin >= '"+cluti.FormatearFecha(this.jFormattedTextField1.getText())+"' and r.fechafin <= '"+cluti.FormatearFecha(this.jFormattedTextField2.getText())+"'");
            ob=q31.uniqueResult();
            float egr1=Float.parseFloat("0.0");
            if(ob != null)
                egr1=Float.parseFloat(ob.toString());
            
            SQLQuery q32=Sesion.createSQLQuery("select sum(mx.cantidad*mx.precio) as suma from multa as m inner join subresxmul as mx on m.idmulta = mx.idmulta inner join subreserva as s on mx.idsubres = s.idsubres inner join reservacion as r on r.idres = s.idres where r.fechafin >= '"+cluti.FormatearFecha(this.jFormattedTextField1.getText())+"' and r.fechafin <= '"+cluti.FormatearFecha(this.jFormattedTextField2.getText())+"'");
            ob=q32.uniqueResult();
            if(ob != null)
                egr1=egr1+Float.parseFloat(ob.toString());
            Sesion.getTransaction().commit();
            //////////////////////////////egreso2///////////////////////////////
            SQLQuery q4=Sesion.createSQLQuery("select sum(m.montogs) from movcaja as m inner join tipomov as t on t.idtipomov = m.idtipomov where t.egreso = '1' and m.feyhomov >= '"+cluti.FormatearFecha(this.jFormattedTextField1.getText())+"' and m.feyhomov <= '"+cluti.FormatearFecha(this.jFormattedTextField2.getText())+"'");
            ob=q4.uniqueResult();
            float egr2=Float.parseFloat("0.0");
            if(ob != null)
                egr2=Float.parseFloat(ob.toString());
             //////////////////////////////ingreso3///////////////////////////////
            SQLQuery q5=Sesion.createSQLQuery("select sum(a.cant*a.valor) from ajustestock as a inner join motivoajuste as m on a.idmoti = m.idmoti where m.aumenta = '0' and m.egreso = '1' and a.feyho >= '"+cluti.FormatearFecha(this.jFormattedTextField1.getText())+"' and a.feyho <= '"+cluti.FormatearFecha(this.jFormattedTextField2.getText())+"'");
            ob=q5.uniqueResult();
            float egr3=Float.parseFloat("0.0");
            if(ob != null)
                egr3=Float.parseFloat(ob.toString());
            //////////////////////////////ingreso3///////////////////////////////
            SQLQuery q6=Sesion.createSQLQuery("select sum(d.cantidaddesc*d.valordesc) from descartes as d where d.fechadesc >= '"+cluti.FormatearFecha(this.jFormattedTextField1.getText())+"' and d.fechadesc <= '"+cluti.FormatearFecha(this.jFormattedTextField2.getText())+"'");
            ob=q6.uniqueResult();
            float egr4=Float.parseFloat("0.0");
            if(ob != null)
                egr4=Float.parseFloat(ob.toString());
            Map param = new HashMap();
            param.put("ing1",ing1);
            param.put("ing2",ing2);
            param.put("egr1",egr1);
            param.put("egr2",egr2);
            param.put("egr3",egr3);
            param.put("egr4",egr4);
            param.put("titulo","Informe de Ingresos y Egresos entre "+this.jFormattedTextField1.getText()+" y "+this.jFormattedTextField2.getText());
            cr.MostrarReporte("repoIngEgrGral", "Informe de Ingresos y egresos",param);
        }
        if(this.jRadioButton2.isSelected() && this.jFormattedTextField1.getText().equals("  /  /    ")==false && this.jFormattedTextField2.getText().equals("  /  /    ")==false){
            Map param = new HashMap();
            param.put("fecha1",cluti.FormatearFecha(this.jFormattedTextField1.getText()));
            param.put("fecha2",cluti.FormatearFecha(this.jFormattedTextField2.getText()));
            param.put("titulo","Ingresos por cobros realizados entre "+this.jFormattedTextField1.getText()+" y "+this.jFormattedTextField2.getText());
            cr.MostrarReporte("repoIngEgr1", "Informe de Ingresos por cobros realizados",param);
        }
        if(this.jRadioButton3.isSelected() && this.jFormattedTextField1.getText().equals("  /  /    ")==false && this.jFormattedTextField2.getText().equals("  /  /    ")==false){
            Map param = new HashMap();
            param.put("fecha1",cluti.FormatearFecha(this.jFormattedTextField1.getText()));
            param.put("fecha2",cluti.FormatearFecha(this.jFormattedTextField2.getText()));
            param.put("titulo","Ingresos por Ajustes (+) de stock entre "+this.jFormattedTextField1.getText()+" y "+this.jFormattedTextField2.getText());
            cr.MostrarReporte("repoIngEgr2", "Informe de Ingresos por Ajustes de Stock",param);
        }
        if(this.jRadioButton4.isSelected() && this.jFormattedTextField1.getText().equals("  /  /    ")==false && this.jFormattedTextField2.getText().equals("  /  /    ")==false){
            Map param = new HashMap();
            param.put("fecha1",cluti.FormatearFecha(this.jFormattedTextField1.getText()));
            param.put("fecha2",cluti.FormatearFecha(this.jFormattedTextField2.getText()));
            param.put("titulo","Egresos por venta de Productos y Servicios entre "+this.jFormattedTextField1.getText()+" y "+this.jFormattedTextField2.getText());
            cr.MostrarReporte("repoIngEgr3", "Informe de Egresos por venta de Productos y Servicios",param);
        }
        if(this.jRadioButton5.isSelected() && this.jFormattedTextField1.getText().equals("  /  /    ")==false && this.jFormattedTextField2.getText().equals("  /  /    ")==false){
            Map param = new HashMap();
            param.put("fecha1",cluti.FormatearFecha(this.jFormattedTextField1.getText()));
            param.put("fecha2",cluti.FormatearFecha(this.jFormattedTextField2.getText()));
            param.put("titulo","Egresos por asignación de multas entre "+this.jFormattedTextField1.getText()+" y "+this.jFormattedTextField2.getText());
            cr.MostrarReporte("repoIngEgr4", "Informe de Egresos por asignación de multas",param);
        }
        if(this.jRadioButton6.isSelected() && this.jFormattedTextField1.getText().equals("  /  /    ")==false && this.jFormattedTextField2.getText().equals("  /  /    ")==false){
            Map param = new HashMap();
            param.put("fecha1",cluti.FormatearFecha(this.jFormattedTextField1.getText()));
            param.put("fecha2",cluti.FormatearFecha(this.jFormattedTextField2.getText()));
            param.put("titulo","Egresos registrados por movimientos de caja entre "+this.jFormattedTextField1.getText()+" y "+this.jFormattedTextField2.getText());
            cr.MostrarReporte("repoIngEgr5", "Informe de Egresos registrados por movimientos de caja",param);
        }
        if(this.jRadioButton7.isSelected() && this.jFormattedTextField1.getText().equals("  /  /    ")==false && this.jFormattedTextField2.getText().equals("  /  /    ")==false){
            Map param = new HashMap();
            param.put("fecha1",cluti.FormatearFecha(this.jFormattedTextField1.getText()));
            param.put("fecha2",cluti.FormatearFecha(this.jFormattedTextField2.getText()));
            param.put("titulo","Egresos por Ajustes (-) de stock entre "+this.jFormattedTextField1.getText()+" y "+this.jFormattedTextField2.getText());
            cr.MostrarReporte("repoIngEgr6", "Informe de Egresos por Ajustes de Stock",param);
        }
        if(this.jRadioButton8.isSelected() && this.jFormattedTextField1.getText().equals("  /  /    ")==false && this.jFormattedTextField2.getText().equals("  /  /    ")==false){
            Map param = new HashMap();
            param.put("fecha1",cluti.FormatearFecha(this.jFormattedTextField1.getText()));
            param.put("fecha2",cluti.FormatearFecha(this.jFormattedTextField2.getText()));
            param.put("titulo","Egresos por Descarte realizados entre "+this.jFormattedTextField1.getText()+" y "+this.jFormattedTextField2.getText());
            cr.MostrarReporte("repoIngEgr7", "Informe de Egresos por Descarte realizados",param);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton6StateChanged

}//GEN-LAST:event_jRadioButton6StateChanged

    private void jRadioButton7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton7StateChanged
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButton7StateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                                                                    //al iniciar el form
        this.setLocationRelativeTo(null);  //centra el objeto en pantalla
        this.setResizable(false);
       // setDefaultCloseOperation(0);
        this.actualizarFechaDeHoy();
        jFormattedTextField1.setText(cluti.ObtenerFechaSinGuion(fechadehoy));
        try {
            Calendar man = cluti.Date_Calender(cluti.StrDMA_Date(fechadehoy));
            man.add(Calendar.DATE, 1);
            String manhana=cluti.Date_StringDMA(clasesutiles.Calender_Date(man));
            jFormattedTextField2.setText(cluti.ObtenerFechaSinGuion(manhana));
        } catch (ParseException ex) {
           //Logger.getLogger(FrmReserva.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton8StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton8StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8StateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmInformeIngresosEgresos dialog = new FrmInformeIngresosEgresos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton9;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    // End of variables declaration//GEN-END:variables

}
